version: '3.9'

services:
  web:
    container_name: jekyll_gh
    build:
      args:
        USER_ID: ${UID?err}
        GROUP_ID: ${GID?err}
        USER_NAME: ${USER_NAME?err}
        GROUP_NAME: ${GROUP_NAME?err}
    # command: ["sleep", "infinity"]
    command: ["bundle", "exec", "jekyll", "serve", "-l", "--host", "0.0.0.0", "--source", "/home/${USER_NAME}/jekyll"]
    volumes:
      - type: bind
        source: ./docs
        target: /home/${USER_NAME}/jekyll
    ports:
      - "4000:4000"
      - "35729:35729"
